modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="${mod_logo_file}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="etched"
    mandatory=true
    versionRange="[1.20.1-2.1.2,)"
    ordering="AFTER"
    side="BOTH"

# Зависимость от Sophisticated Core
[[dependencies.${mod_id}]]
    modId="sophisticatedcore"
    mandatory=true
    versionRange="[0.6.64.717,)"
    ordering="AFTER"
    side="BOTH"

# Зависимость от Sophisticated Backpacks
[[dependencies.${mod_id}]]
    modId="sophisticatedbackpacks"
    mandatory=true
    versionRange="[3.21.1.1118,)"
    ordering="AFTER"
    side="BOTH"

MixinConfigs = "sophisticatedbackpacksetchedintegration.mixins.json"
